### ISSUE TITLE
A flag to perform `git mv`

### ISSUE THREAD

**Issue by kovmir** [itchyny/mmv#18] opened 2022-08-28 13:15 UTC
It would be great to be able to invoke `mmv --git` to perform `git mv` instead of traditional renaming.

**Comment by itchyny** [comment] 2022-08-28 13:29
The goal of this tool is simplicity that just executes multiple file moves. Relying another command grows the dependency and brings complexity. This is a duplicate of #12, and still unlikely to support in this project.

**Closed as not planned by itchyny** 2022-08-28 13:29 UTC

**Comment by kovmir** [comment] 2022-08-29 06:41
FYI and #12: I have discovered, it is achievable without additional contributions to `mmv`. Simply rename the files, and then stage both the new, and deleted ones. `git` is smart enough to interpret this as a rename.
